GET http://localhost:3000/users/

###
GET http://localhost:3000/users/1

###
POST http://localhost:3000/users/
 Content-Type: application/json

 {
    "username": "DIana",
    "password": "chasss",
    "email": "diana@gmail.com"
 }

###
PUT http://localhost:3000/users/3
 Content-Type: application/json

 {
    "username": "Daniel",
    "password": "Cass",
    "email": "russel@gmail.com"
 }

###
DELETE http://localhost:3000/users/2/

###
POST http://localhost:3000/users/
Content-Type: application/json

{
  "username": "Ana",
  "password": "kaseina",
  "email": "ana@gmail.com"
  //para decifrar la contraseña
}

###

POST http://localhost:3000/users/login
Content-Type: application/json

{
  "username": "Ana",
  "password": "123456"
  //para iniciar el login
}

###
PUT http://localhost:3000/users/1/password
Content-Type: application/json

{
  "newPassword": "123456"
}

//hacer los endpouint para la tabla staff

// nota hacer 3 archivos staff en la carpeta controllers, models y routes... en ek server agrregar la ruta de staff
// rutas de prueba para la tabla staff
###
GET http://localhost:3000/staff/

###
GET http://localhost:3000/staff/3

###
POST http://localhost:3000/staff/
Content-Type: application/json

{
   "first_name": "Angela",
   "last_name": "Garcia",
   "birth_date": "1997-04-02",
   "gender": "F",
   "phone_number": "2871540220",
   "email": "angel@gmail.com",
   "address": "Calle 4",
   "user_id": 3
}
 
###
PUT http://localhost:3000/staff/3
Content-Type: application/json

{
   "first_name": "Sara",
   "last_name": "Russell",
   "birth_date": "1982-07-15",
   "gender": "F",
   "phone_number": "2468543222",
   "email": "jane.smith@gmail.com",
   "address": "Casas geo",
   "user_id": 1
}

###
DELETE http://localhost:3000/staff/2
